services:
  searxng:
    image: searxng/searxng:2024.12.0
    container_name: market-orca-searxng
    restart: unless-stopped
    ports:
      - "18080:8080"
    environment:
      - SEARXNG_BASE_URL=https://searxng.anomali.web.id/
    volumes:
      - ./searxng/settings.yml:/etc/searxng/settings.yml
