module.exports = {
  apps: [
    {
      name: 'market-orca-api',
      script: './backend/src/server.js',
      cwd: '/home/dicky/.openclaw/workspace/market-orca',
      env: { PORT: 4567 },
      max_restarts: 10,
      min_uptime: '10s',
      restart_delay: 5000,
      max_memory_restart: '400M',
      kill_timeout: 5000,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: '/tmp/market-orca-api-error.log',
      out_file: '/tmp/market-orca-api-out.log',
      autorestart: true,
    },
    {
      name: 'report-server',
      script: './backend/src/report-server.js',
      cwd: '/home/dicky/.openclaw/workspace/market-orca',
      env: { PORT: 4568 },
      max_restarts: 10,
      restart_delay: 5000,
      max_memory_restart: '300M',
      kill_timeout: 5000,
      error_file: '/tmp/report-server-error.log',
      out_file: '/tmp/report-server-out.log',
      autorestart: true,
    },
    {
      name: 'mcp-server',
      script: './backend/src/mcp-http-server.js',
      cwd: '/home/dicky/.openclaw/workspace/market-orca',
      env: { MCP_PORT: 1788, MCP_HOST: '127.0.0.1' },
      max_restarts: 10,
      restart_delay: 5000,
      kill_timeout: 5000,
      error_file: '/tmp/mcp-server-error.log',
      out_file: '/tmp/mcp-server-out.log',
      autorestart: true,
    },
    {
      name: 'mcp-n8n-bridge',
      script: './backend/src/n8n-mcp-bridge.js',
      cwd: '/home/dicky/.openclaw/workspace/market-orca',
      env: { PORT: 1789 },
      max_restarts: 5,
      restart_delay: 5000,
      kill_timeout: 5000,
      error_file: '/tmp/mcp-n8n-error.log',
      out_file: '/tmp/mcp-n8n-out.log',
      autorestart: true,
    },
  ]
}
