import { execFile } from 'node:child_process'
import { promisify } from 'node:util'
import dns from 'node:dns/promises'
import net from 'node:net'
import { db } from './db.js'
import { upsertRagDocument } from './rag.js'

const execFileAsync = promisify(execFile)
const ALLOWED = (process.env.RAG_ALLOWED_DOMAINS || 'idx.co.id,bi.go.id,ojk.go.id,kontan.co.id,bisnis.com,cnbcindonesia.com,katadata.co.id,detik.com,reuters.com,bloomberg.com,marketwatch.com,techcrunch.com,theverge.com,technologyreview.com,arstechnica.com,github.com,huggingface.co,coindesk.com,cnbc.com,reddit.com,medium.com,dev.to,news.ycombinator.com,stackoverflow.com,substack.com,ft.com,wsj.com,investing.com,tradingview.com,seekingalpha.com,investopedia.com,fool.com,barrons.com,nasdaq.com,nyse.com,cointelegraph.com,decrypt.co,theblock.co,bankless.com,defillama.com,arxiv.org,paperswithcode.com,openreview.net,semianalysis.com,stratechery.com,platformer.news,venturebeat.com,zdnet.com,bleepingcomputer.com,krebsonsecurity.com,darkreading.com,pubmed.ncbi.nlm.nih.gov,ncbi.nlm.nih.gov,plos.org,biorxiv.org,medrxiv.org,osf.io,zenodo.org,figshare.com,dataverse.harvard.edu,kaggle.com,data.gov,data.go.id,perpusnas.go.id,rama.kemdikbud.go.id,garuda.kemdikbud.go.id,neliti.com,onesearch.id,repository.ugm.ac.id,repository.ui.ac.id,repository.itb.ac.id,repository.unair.ac.id,repository.ipb.ac.id,repository.its.ac.id,eprints.undip.ac.id,journal.ui.ac.id,journal.ugm.ac.id,journal.itb.ac.id,sinta.kemdikbud.go.id,hubspot.com,semrush.com,ahrefs.com,moz.com,searchengineland.com,thinkwithgoogle.com,ads.google.com,developers.google.com,business.instagram.com,business.facebook.com,ads.tiktok.com,linkedin.com,sproutsocial.com,hootsuite.com,buffer.com,contentmarketinginstitute.com,backlinko.com,wordstream.com,hotjar.com,mixpanel.com,amplitude.com,github.blog,docs.github.com,git-scm.com,docker.com,kubernetes.io,cncf.io,prometheus.io,grafana.com,postgresql.org,sqlite.org,redis.io,bun.sh,deno.com,typescriptlang.org,react.dev,vuejs.org,astro.build,vite.dev,tailwindcss.com,hono.dev,drizzle.team,ollama.com,modelcontextprotocol.io,docs.anthropic.com,platform.openai.com,ai.google.dev,docs.perplexity.ai').split(',').map(s=>s.trim()).filter(Boolean)

export function initCrawlQueue(){ db.exec(`CREATE TABLE IF NOT EXISTS rag_crawl_queue (id INTEGER PRIMARY KEY AUTOINCREMENT,url TEXT UNIQUE NOT NULL,source TEXT DEFAULT '',asset_tags TEXT DEFAULT '',status TEXT NOT NULL DEFAULT 'pending',attempts INTEGER NOT NULL DEFAULT 0,last_error TEXT DEFAULT '',next_attempt_at TEXT DEFAULT (datetime('now')),created_at TEXT DEFAULT (datetime('now')),updated_at TEXT DEFAULT (datetime('now')));`) }
export function normalizeUrl(url){ const u=new URL(url); u.hash=''; ['utm_source','utm_medium','utm_campaign','utm_term','utm_content','fbclid','gclid'].forEach(k=>u.searchParams.delete(k)); return u.toString() }
function isPrivateIp(ip){ if(!ip) return true; if(ip==='127.0.0.1'||ip==='::1') return true; if(net.isIP(ip)===4){ const [a,b]=ip.split('.').map(Number); return a===10 || (a===172&&b>=16&&b<=31) || (a===192&&b===168) || a===169&&b===254 || a===127 } return /^fc|^fd|^fe80/i.test(ip) }
export async function isAllowedSource(url){ let u; try{u=new URL(url)}catch{return {ok:false,reason:'invalid_url'}}; if(!['http:','https:'].includes(u.protocol)) return {ok:false,reason:'bad_protocol'}; if(['localhost','127.0.0.1','0.0.0.0','::1'].includes(u.hostname)) return {ok:false,reason:'local_blocked'}; const allowed=ALLOWED.some(d=>u.hostname===d||u.hostname.endsWith('.'+d)); if(!allowed) return {ok:false,reason:'domain_not_allowed'}; try{ const addrs=await dns.lookup(u.hostname,{all:true}); if(addrs.some(a=>isPrivateIp(a.address))) return {ok:false,reason:'private_ip_blocked'} }catch{return {ok:false,reason:'dns_failed'}}; return {ok:true,host:u.hostname} }
export async function crawlWithCrawl4ai(url){ const {stdout}=await execFileAsync('crwl',['crawl',url,'-o','markdown'],{timeout:20000,maxBuffer:1024*1024}); return stdout }
export async function fetchCleanHtml(url){ const r=await fetch(url,{signal:AbortSignal.timeout(15000),headers:{'user-agent':'MarketOrcaBot/1.0'}}); if(!r.ok) throw new Error(`fetch_${r.status}`); const html=await r.text(); return html.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim().slice(0,50000) }
export async function crawlUrl(url){ const policy=await isAllowedSource(url); if(!policy.ok) throw new Error(policy.reason); const normalized=normalizeUrl(url); let content=''; let method='crawl4ai'; try{ content=await crawlWithCrawl4ai(normalized) } catch(e){ method='fetch'; content=await fetchCleanHtml(normalized) } return {url:normalized,content,method,source:policy.host} }
export function enqueueRagCrawl(url,{source='',assetTags=[]}={}){ initCrawlQueue(); const tags=Array.isArray(assetTags)?assetTags.join(','):String(assetTags||''); db.prepare(`INSERT INTO rag_crawl_queue (url,source,asset_tags,status,updated_at) VALUES (?,?,?,'pending',datetime('now')) ON CONFLICT(url) DO UPDATE SET status='pending', source=excluded.source, asset_tags=excluded.asset_tags, updated_at=datetime('now')`).run(url,source,tags); return {ok:true,url} }
export async function runRagCrawlWorker({limit=3}={}){ initCrawlQueue(); const rows=db.prepare(`SELECT * FROM rag_crawl_queue WHERE status IN ('pending','retry') AND datetime(next_attempt_at)<=datetime('now') ORDER BY id ASC LIMIT ?`).all(limit); const results=[]; for(const row of rows){ try{ db.prepare(`UPDATE rag_crawl_queue SET status='running',updated_at=datetime('now') WHERE id=?`).run(row.id); const crawled=await crawlUrl(row.url); const doc=upsertRagDocument({url:crawled.url,title:row.source||crawled.source,source:crawled.source,publishedAt:'',content:crawled.content,assetTags:String(row.asset_tags||'').split(',').filter(Boolean)}); db.prepare(`UPDATE rag_crawl_queue SET status='done',last_error='',updated_at=datetime('now') WHERE id=?`).run(row.id); results.push({url:row.url,ok:true,method:crawled.method,doc}) }catch(e){ const attempts=row.attempts+1; const status=attempts>=3?'failed':'retry'; db.prepare(`UPDATE rag_crawl_queue SET status=?, attempts=?, last_error=?, next_attempt_at=datetime('now', ?), updated_at=datetime('now') WHERE id=?`).run(status,attempts,String(e.message||e).slice(0,300),`+${attempts*30} minutes`,row.id); results.push({url:row.url,ok:false,error:String(e.message||e)}) } } return {ok:true,processed:results.length,results} }
