use_default_settings: true
server:
  secret_key: "market-orca-searxng-2026"
  limiter: false
  image_proxy: false
search:
  safe_search: 0
  autocomplete: "duckduckgo"
  formats:
    - html
    - json
outgoing:
  request_timeout: 10.0
  max_request_timeout: 15.0
engines:
  - name: google
    disabled: false
  - name: google news
    disabled: false
  - name: bing
    disabled: false
  - name: duckduckgo
    disabled: false
  - name: duckduckgo news
    disabled: false
  - name: yahoo
    disabled: false
  - name: wikipedia
    disabled: false

ui:
  static_path: "/usr/local/searxng/searx/static"
  default_locale: ""
  theme: "simple"
general:
  instance_name: "Market Orca Search"
  debug: false
