use_default_settings: true
server:
  secret_key: "market-orca-aroxng-2026-static"
  base_url: "https://searxng.anomali.web.id/"
  bind_address: "127.0.0.1"
  limiter: false
  image_proxy: false
ui:
  static_use_hash: true
  default_theme: simple
search:
  safe_search: 0
  autocomplete: "duckduckgo"
  formats:
    - html
    - json
outgoing:
  request_timeout: 10.0
  max_request_timeout: 15.0
engines:
  - name: google
    disabled: false
  - name: google news
    disabled: false
  - name: bing
    disabled: false
  - name: duckduckgo
    disabled: false
  - name: brave
    disabled: false
  - name: wikipedia
    disabled: false
